{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gnocpush.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "gnocpush.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
      {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 -}}
    {{- end }}
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "gnocpush.selectorLabels" . | nindent 6 }}
{{- end }}
